export const IMAGE_LIMITS = {
  MIN_IMAGES: 2,
  MAX_IMAGES: 6
} as const

export const BOTTOM_NAV_HEIGHT = 80

export const TESTING_TUTORIAL = false 

export const PROFILES_PER_PAGE = 1

export const RECREATIONAL_INTERESTS = [
  'Sport / Fitness',
  'Gym',
  'Gaming',
  'Bars',
  '420',
  'Fotografie',
  'Musik machen',
  'Musik hören',
  'Coffee',
  'Tanzen',
  'Mit Freunden',
  'Kochen & Backen',
  'Reisen & Kultur',
  'Clubbing',
  'Raves',
  'Filme & Serien',
  'Kunst',
  'Wandern & Outdoor',
  'Tabletop',
  'Ehrenamt',
  'Religion'
] as const

export const ACADEMIC_INTERESTS = [
  'Wissenschaftliches Schreiben',
  'Forschungsprojekte',
  'Programmierung & IT',
  'Sprachen lernen',
  'Debattieren & Rhetorik',
  'Studentische Initiativen',
  'Akademische Workshops',
  'Fachschaftsarbeit',
  'Laborarbeit & Experimente',
  'Wissenschaftliche Publikationen',
  'Interdisziplinäre Projekte',
  'Konferenzen & Fachvorträge'
] as const

export const INTERESTS = [
  ...RECREATIONAL_INTERESTS,
  ...ACADEMIC_INTERESTS
] as const 

export const PREFRENCES = [
  "Lerngruppen oder Lernpartner",
  "Nachhilfe anbieten oder suchen",
  "Studentenpartys & Feiern gehen",
  "Studiengangübergreifende Kontakte",
  "Projekt oder Startup Partner",
  "Gaming & E-Sports Gruppen",
] as const

export const MAJORS = [
  'African Languages and Cultures',
  'Afrikanische Sprachen im Kontext',
  'Afrikanische Sprachen und Kulturen',
  'Allgemeine Sprachwissenschaft',
  'Althebraistik',
  'Anglistik / Amerikanistik',
  'Arbeit, Wirtschaft, Gesellschaft',
  'Archäologie und Kulturgeschichte des antiken Mittelmeerraumes',
  'Atmospheric Science',
  'Betriebswirtschaft',
  'Bewegungswissenschaft',
  'Bioinformatik',
  'Biologie',
  'Bioressourcennutzung',
  'British and American Cultures',
  'Buddhist Studies',
  'Business Mathematics',
  'Chemie',
  'Computing in Science',
  'Data Science and Artificial Intelligence',
  'Deutsche Sprache und Literatur',
  'Deutsches Recht',
  'Deutschsprachige Literaturen',
  'Digital- und Medienmanagement',
  'Dokumentation und Analyse Afrikanischer Sprachen',
  'Economics',
  'Empirische Kulturwissenschaft',
  'English as a World Language',
  'Erziehungs- und Bildungswissenschaft',
  'Ethiopian Studies',
  'Ethnolinguistik bedrohter Sprachen',
  'Ethnologie',
  'Europäisches Wirtschaftsrecht',
  'Europastudien',
  'European and European Legal Studies',
  'European Master in Classical Cultures',
  'Evangelische Theologie',
  'Französisch',
  'Gebärdensprachdolmetschen',
  'Gebärdensprachen',
  'Gemeinsamer Studiengang Rechtswissenschaft',
  'General Management',
  'Geographie',
  'Geophysik',
  'Geowissenschaften',
  'Germanistische Linguistik',
  'Geschichte',
  'Geschichte der Naturwissenschaften',
  'Geschichte, Sprachen und Kulturen des Vorderen Orients',
  'Gesundheitsmanagement',
  'Griechische und Lateinische Philologie',
  'Health Economics & Health Care Management',
  'Higher Education',
  'Historische Musikwissenschaft',
  'Holzwirtschaft',
  'Human Resource Management',
  'Human Rights and Democratisation',
  'Indology and Tibetology',
  'Industrial Mathematics',
  'Informatik',
  'Innovation, Business and Sustainability',
  'Integrated Climate System Sciences',
  'Integrative Lerntherapie',
  'Intelligent Adaptive Systems',
  'Interdisziplinäre Public und Nonprofit Studien',
  'International Taxation',
  'Internationale Kriminologie',
  'Iranistik',
  'Islamwissenschaft',
  'IT-Management und -Consulting',
  'Italienisch',
  'Japanologie',
  'Journalism, Media and Globalisation',
  'Journalistik und Kommunikationswissenschaft',
  'Judaistik',
  'Jüdische Philosophie und Religion',
  'Katalanisch',
  'Katholische Theologie',
  'Klassische Archäologie',
  'Klassische Philologie',
  'Koreanistik',
  'Kosmetikwissenschaft',
  'Kriminologie',
  'Kunstgeschichte',
  'Languages and Cultures of Southeast-Asia',
  'Lateinamerika-Studien',
  'Law and Economics',
  'Lebensmittelchemie',
  'Lehramt an Beruflichen Schulen',
  'Lehramt an berufsbildenden Schulen',
  'Lehramt an Grundschulen',
  'Lehramt an Gymnasien',
  'Lehramt der Primar- und Sekundarstufe',
  'Lehramt für Sonderpädagogik',
  'Liberal Arts & Sciences',
  'Literatur, Sprache und Kultur des modernen Griechenlands',
  'Manuskriptkulturen',
  'Marine Ecosystem and Fisheries Science',
  'Marine Ökosystem- und Fischereiwissenschaften',
  'Mathematical Physics',
  'Mathematics',
  'Mathematik',
  'MathMods - Mathematical Modelling in Engineering',
  'Medienwissenschaft',
  'Medizin',
  'Mehrsprachigkeit und Bildung',
  'Mensch-Computer-Interaktion',
  'Meteorologie',
  'Mittelalter-Studien',
  'Molecular Life Sciences',
  'Molecular Plant Science',
  'Molekularbiologie',
  'Nanowissenschaften',
  'Neogräzistik und Byzantinistik',
  'Ocean and Climate Physics',
  'Ostasien',
  'Osteuropastudien',
  'Pädagogik bei Behinderung',
  'Peace and Security Studies',
  'Performance Studies',
  'Pharmazie',
  'Philosophie',
  'Physics',
  'Physik',
  'Politics, Economics, Philosophy',
  'Politikwissenschaft',
  'Portugiesisch',
  'Psychologie',
  'Rechtswissenschaft',
  'Religionen, Dialog und Bildung',
  'Religionswissenschaft',
  'Romanische Literaturen',
  'Romanistische Linguistik',
  'Sinologie',
  'Slavistik',
  'Software-System-Entwicklung',
  'South Asian Studies',
  'Sozialökonomie',
  'Soziologie',
  'Spanisch',
  'Sprachen und Kulturen finnisch-ugrischer und sibirischer Völker',
  'Sprachen und Kulturen Indiens und Tibets',
  'Sprachen und Kulturen Südostasiens',
  'Systematische Musikwissenschaft',
  'Technomathematik',
  'Tibetan Studies',
  'Turkologie',
  'Versicherungsrecht',
  'Volkswirtschaftslehre',
  'Vor- und Frühgeschichtliche Archäologie',
  'Wirtschaft und Kultur Chinas',
  'Wirtschaftsinformatik',
  'Wirtschaftsingenieurwesen',
  'Wirtschaftsmathematik',
  'Wood Science'
] as const


export type Major = typeof MAJORS[number]